import localFont from "next/font/local";
import "./globals.css";
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import { NextUISProviders } from "./providers/NextUIProviders";
import { PageLoadProvider } from "./providers/PageLoadProvider";
import Providers from "./Redux/Providers";
import Layout from "@/components/Layout/Layout";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ToastContainer />
          <Providers>  
            <NextUISProviders> 
              <PageLoadProvider> 
                <Layout>   
                  {children} 
                </Layout>   
              </PageLoadProvider>       
            </NextUISProviders> 
          </Providers>  
      </body>
    </html>
  );
}
